title: "<h3>Weill Cornell Medicine CTSC Virtual Seminar Series</h3><br>Generative AI and Large Language Models"
description: "CTIV 5057"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
